### ISSUE TITLE
Add release information to published assemblies

### ISSUE THREAD

**Issue by stewartanderson3** [stewie1570/tetris#187]
Set a GIT_TAG command to something like:
```
GIT_TAG=$(git describe --tags --abbrev=0)
```

Suffix the dotnet publish command with something like:
```
/p:AssemblyVersion=1.2.3.4 /p:Version=1.2.3.4-product-version
```

**Comment by stewie1570** [comment]
Git isn't available. This is too much of a pain in the ass to do in Heroku right now.
